name: Container-image
on: [push]
jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: rekonuk/cert-manager-webhook-gandi
        username: restd
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        buildoptions: "--compress --force-rm"
        tag_names: true
